assy/urls.py
from django.urls import path, include
from . import views
from .views import HomeList, PostCreate, PostDelete, ProfileUpdate, chat
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('assy/home/', HomeList.as_view(), name='home'),
    path('assy/post/', PostCreate.as_view(), name='post'),
    path('assy/demo/', views.demo, name='demo'),
    path('assy/profile/<int:pk>', ProfileUpdate.as_view(), name='profile'),
    path('assy/delete/<int:pk>', PostDelete.as_view(), name='delete'),
    path('assy/chat/<str:username>/', views.chat, name='chat'),
 ] +  static(settings.IMAGE_URL, document_root=settings.IMAGE_ROOT)

sns/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('assy.urls')),
    path('accounts/', include('allauth.urls')),
    path('accounts/login/', TemplateView.as_view(template_name = 'accounts/login.html'), name='login'),
    path('accounts/logout/', TemplateView.as_view(template_name = 'logout.html'), name='logout'),
    path('accounts/signup/', TemplateView.as_view(template_name = 'signup.html'), name='signup'),
    path('accounts/password_reset/', views.PasswordResetView.as_view(template_name='account/password/reset.html'), name='reset'),
    path('accounts/password_reset/done/', views.PasswordResetDoneView.as_view(template_name='account/password/reset_done.html'), name="reset_done"),
    path('accounts/password_reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(template_name="account/password/reset_confirm.html"), name="reset_confifm"),
    #path('accounts/reset/done/', .as_view(template_name='account/password_change_done.html'), name="password_change_done")
]

assy/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator
import uuid
# Create your models here.


GENDER_CHOICES = (
        (1, '男性'),
        (2, '女性'),
    )

class CustomUser(AbstractUser):

    class Meta(AbstractUser.Meta):
        db_table = 'auth_user'
        verbose_name_plural = 'CustomUser'

    age = models.IntegerField(blank=True, default=0,validators=[MinValueValidator(20),MaxValueValidator(99)])
    gender = models.IntegerField(choices=GENDER_CHOICES, blank=True, default=0)
    img = models.TextField(blank=True, default='icon_default.jpg')
    image = models.ImageField(upload_to='images/', verbose_name="画像", blank=True, null=True)

class PostContents(models.Model):
    post_id = models.AutoField(primary_key=True)
    #user_id = models.IntegerField(null=True)
    username = models.CharField(max_length=100, null=True)
    contents = models.TextField()
    member = models.IntegerField(null=True)
    reward = models.CharField(max_length=30)
    place = models.CharField(max_length=30)
    date = models.DateTimeField()
    post_time = models.DateTimeField(default=timezone.now)
    image = models.ImageField(upload_to='images/', verbose_name='画像', null=True)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.post_id)

class RoomModel(models.Model):
    room_id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    name = models.CharField(max_length=100, null=True)
    request_user = models.CharField(max_length=100, null=True)
    request_id = models.IntegerField(null=True)
    chat_time = models.DateTimeField(default=timezone.now)
    #post = models.ForeignKey(PostContents, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.room_id)
 
class Message(models.Model):
    message_id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    room = models.CharField(max_length=100, null=True)
    request_user = models.CharField(max_length=100, null=True)
    #room = models.ForeignKey(RoomModel, blank=True, null=True, related_name='room_messages', on_delete=models.CASCADE)
    content = models.TextField(null=True)
    message_history = models.CharField(max_length=100, null=True)
    created_at = models.DateTimeField(default=timezone.now, null=True)

    def __str__(self):
        return str(self.message_id)

assy/forms.py
from allauth.account.forms import SignupForm
from django import forms
from .models import CustomUser, PostContents, RoomModel, Message
from allauth.account.adapter import DefaultAccountAdapter
from django.core.validators import MaxValueValidator, MinValueValidator


class CustomSignupForm(SignupForm):
    data = [
        ( 1, '男性'),
        ( 2 , '女性'),
    ]
    #email = forms.EmailField(label='hello')
    gender = forms.ChoiceField(choices=data) 
    age = forms.IntegerField(validators=[MinValueValidator(20),MaxValueValidator(99)])
    image = forms.ImageField()

    class Meta:
        model = CustomUser

    def signup(self, request,user):
        user.age = self.cleaned_data['age']
        user.gender = self.cleaned_data['gender']
        user.image = self.cleaned_data['image']
        user.save()
        return user
        
#投稿フォーム
class CreateForm(forms.ModelForm):
    class Meta:
        model = PostContents
        fields = ('place','date','member','contents')
        widgets = {
            'place': forms.TextInput(attrs={'placeholder':'例）○○駅'}),
            'date': forms.DateTimeInput(attrs={'placeholder': '例）yyyy-mm-dd hh:mm:ss'}),
            'contents': forms.TextInput(attrs={'placeholder':'例）終電なくしたので誰か迎えにきてください。'})
        }

#プロフィール編集フォーム
class ProfileForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username','email','age','gender','image')

#チャットフォーム
class RoomForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ('room','content','message_history')
        widgets = {
            'message_history': forms.TextInput(attrs={'disabled':'desabled'})
        }

assy/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from .models import PostContents, CustomUser, RoomModel, Message
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from .forms import CreateForm, ProfileForm, RoomForm
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.contrib import messages
from django.http import HttpResponse
from django.template import loader

#ホーム画面
class HomeList(ListView):
    template_name = 'assy/home.html'
    model = CustomUser
        
    def get_context_data(self, **kwargs):
        sql = PostContents.objects.select_related('user').order_by('-post_time')
        context = super().get_context_data(**kwargs)
        context.update({
            'more_context': sql
        })
        return context

#チャット画面
def chat(request, username):
    post = PostContents.objects.filter(username=username)
    roomcnt = RoomModel.objects.filter(name=username,request_user=request.user.username).count()
    if roomcnt == 0 :
        room = RoomModel(name=username, request_user=request.user.username)
        room.save()
    #room.save()
    params = {
        'form': RoomForm(),    #フォーム
        'username': username,    #ユーザー名
        'post': post,
        'chat_list': RoomModel.objects.filter(request_id=request.user.id).order_by('chat_time'),
        'users': CustomUser.objects.all(),
        'message': Message.objects.filter(room=username),
        #'repuest_message': Message.objects.filter(request_user=request.user.username),
        }
    if request.method == 'POST':
        content = request.POST['content']
        message_history = Message(message_history=content, room=username, request_user=request.user.username)
        message_history.save()
    return render(request, 'assy/chat.html', params)  

#新規投稿
class PostCreate(CreateView):
    template_name = 'assy/post.html'
    model = PostContents
    form_class = CreateForm
    success_url = reverse_lazy('home')
    
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user_id = self.request.user.id
        self.object.image = self.request.user.image
        self.object.username = self.request.user.username
        self.object.save()

        messages.success(self.request, "保存しました")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.warning(self.request, form.errors)
        return super().form_invalid(form)

#プロフィール編集
class ProfileUpdate(UpdateView):
    template_name = 'assy/profile.html'
    model = CustomUser
    fields = ('username','age','email','gender','image')
    success_url = reverse_lazy('home')

    #def form_valid(self, form):
    #    self.object = form.save(commit=False)
    #    return super().form_valid(form)
   
#投稿削除
class PostDelete(DeleteView):
    model = PostContents
    success_url = reverse_lazy('home')

def demo(request):
    return render(request, 'assy/demo.html')

templates/assy/chat.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}
<div id="your_container">
        <!-- チャットの外側部分① -->
        <div id="bms_messages_container">
            <!-- ヘッダー部分② -->
            <div id="bms_chat_header">
                <div class="direct">
                    <p>Direct</p>
                </div>
                <!--ステータス-->
                <div id="bms_chat_user_status">
                    <!--ステータスアイコン-->
                    <div id="bms_status_icon">
                        {% for item in post %}
                            <img class="talk_now" src="/{{ item.user.image.url }}">
                        {% endfor %}</div>
                    <!--ユーザー名-->
                    <div id="bms_chat_user_name">{{ username }}</div>
                </div>
            </div>
            <div class="chat_list">
                {% for chat in chat_list %}
                    <div class="chat_member">
                        <a href="{% url 'chat' chat.name %}">
                        {% for user_image in users %}
                            {% if user_image.username == chat.name %}
                            <img class="chat_list_user_img" src="/{{ user_image.image.url }}">
                            {% endif %}
                        {% endfor %}
                        <div class="chat_info">
                            <p class="chat_member_user_name">{{ chat.name }}</p>
                            <p class="chat_comment_history">そしたら２０時でお願いします。</p>
                            <p class="last_chat_time">{{ chat.chat_time|date:"Mj日" }}</p>
                        </div>
            
                        </a>
                    </div>
                {% endfor %}
            </div>
            <!-- タイムライン部分③ -->
            <div id="bms_messages">

                <!--メッセージ１（左側）-->
                {% for messages in message %}
                    {% if messages.room == username and messages.request_user != user.username %}
                    <div class="bms_message bms_left">
                        <div class="bms_message_box">
                            <div class="bms_message_content">
                                <div class="bms_message_text">
                                    <p>{{ messages.message_history }}</p>
                                    <p><small>{{ messages.created_at|date:"j日 G:i" }}</small></p>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                {% endfor %}
                <div class="bms_clear"></div><!-- 回り込みを解除（スタイルはcssで充てる） -->

                <!--メッセージ２（右側）-->
                {% for messages in message %}
                    {% if messages.room == username and messages.request_user == user.username %}
                        <div class="bms_message bms_right">
                            <div class="bms_message_box">
                                <div class="bms_message_content">
                                    <div class="bms_message_text">
                                        <p>{{ messages.message_history }}</p>
                                        <p><small>{{ messages.created_at|date:"j日 G:i" }}</small></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
                
            </div>
            <div class="bms_clear"></div><!-- 回り込みを解除（スタイルはcssで充てる） -->
                <div id="bms_send">
                    <form action="{% url 'chat' username %}" method='post'>{% csrf_token %}
                        <!--<div id="id_message_history"></div>-->
                        {{ form.content }}
                        <input type=submit id="bms_send_btn" value="送信"></button>
                    </form>
            </div>
            <!-- テキストボックス、送信ボタン④ -->
            
        </div>
    </div>






{{ username | json_script:"room-name" }}
    <script>
        const roomName = JSON.parse(document.getElementById('room-name').textContent);

        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/assy/'
            + roomName
            + '/'
        );

        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            document.querySelector('#id_message_history').value += (data.message + '\n');
        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };

        //chat-message-input
        document.querySelector('#id_content').focus();
        document.querySelector('#id_content').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#id_content');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message
            }));
            messageInputDom.value = '';
        };
    </script>
{% endblock content %}

templates/assy/home.html
{% extends "layout.html" %}
{% load static %}


{% block content %}

{% if user.is_authenticated %}

    <div class="consept">
        <div class="flex">
            <img src="{% static 'assy/img/02.jpg' %}" class="header_img" >
            <img src="{% static 'assy/img/01.jpg' %}" class="header_img2">
        </div>
        <p>誰かがきっと、あなたを迎えに来る</p>
    </div>
    <div class="home_content">
        {% for item in more_context %}
        <div class="post_list">
            <div class="image1">
               <img class="user_icon" src="/{{ item.user.image.url }}" width=250px>
            </div>
            <div class="post_info">
                <p class="post_user">{{ item.user.username }}</p>
                <p class="post_place"><strong>場所 :</strong> {{ item.place }}</p>
                <p class="post_people"><strong>人数 :</strong> {{ item.member }}</p>
                <p class="meeting"><strong>時間 :</strong> {{ item.date|date:"n/j G時i分" }}</p>
                <p class="post_comment"><strong>コメント :</strong> {{ item.contents }}</p>
                {% if user.id != item.user_id %}
                <p class="dm"><a href="{% url 'chat' item.username %}"><button type="submit">メッセージを送る</button></a></p>
                {% endif %}
            </div>
            <div class="iitd">
                <p class="post_time">{{ item.post_time|date:"n/j G:i" }}</p>
                {% if user.id == item.user_id %}
                <button type="button" class="button is-light delete-modal-button" data-deleteurl="{% url 'delete' item.pk %}">削除</button>
                <div class="modal" id="modal">
                    <div class="modal-background"></div>
                        <div class="modal-card">
                            <header class="modal-card-head"><p class="modal-card-title">確認</p></header>
                                <section class="modal-card-body">本当に削除してよろしいですか。</section>
                                    <footer class="modal-card-foot">
                                        <form action="" method="POST" id="delete-form">
                                        {% csrf_token %}
                                            <button type="button" class="button is-info" id="delete-cancel-button">キャンセル</button>
                                            <button type="submit" class="button is-danger">削除</button>
                                        </form>
                                    </footer>
                        </div>
                </div>
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
{% else %}
    <p><a href="{% url 'login' %}">ログイン</a></p>
    <p><a href="{% url 'signup' %}">signup</a></p>
{% endif %}
{% endblock %}

{% block extrajs %}
    <script>
        const deleteForm = document.getElementById('delete-form');
        const modal = document.getElementById('modal');
        const deleteCancelButton = document.getElementById('delete-cancel-button');
        const deleteModalButtons = document.getElementsByClassName('delete-modal-button');
        for (const button of deleteModalButtons) {
            button.addEventListener('click', () => {
                modal.classList.add('is-active');
                deleteForm.action = button.dataset.deleteurl;
            });
        }
        deleteCancelButton.addEventListener('click', () => {
            modal.classList.remove('is-active');
        });
    </script>
{% endblock %}

templates/assy/post.html
{% extends 'layout.html' %}
{% load static %}

{% block customcss %}
{% endblock customcss %}

{% block content %}
<div class="post_content">
    <div class="new_post_content">
        <h2>お迎え依頼</h2>
       
            <form action="{% url 'post' %}" method="POST">{% csrf_token %}
                <div class="post_item"><p><strong>場所</strong>&emsp;&emsp;</p>{{ form.place }}</div>
                <div class="post_item"><p><strong>人数</strong>&emsp;&emsp;</p>{{ form.member }}&emsp;人</div>
                <div class="post_item"><p><strong>集合時間</strong></p>{{ form.date }}</div>
                <div class="post_item"><p class="comment"><strong>コメント</strong></p>{{ form.contents }}</div>
                <div class="post_item"><p><input class="btn btn-primary" type="submit" value="投稿" style="margin-right: auto;"></p></div>
            </form>
    </div>
</div>
{% endblock content %}

templates/assy/profile.html
{% extends 'layout.html' %}
{% load static %}


{% block customcss %}
{% endblock customcss %}

{% block content %}
<div class="profile_content">
    <div class="profile_list">
        <h2>プロフィール設定</h2>
        
        <form action="" method='POST' id='myform' enctype="multipart/form-data">{% csrf_token %}
            {% if user.image %}
                <img class="img_update" src="/{{ user.image.url }}" width=250px>
            {% endif %}
            <div class="profile_update">
                <p><strong>プロフィール画像</strong>{{ form.image }}</p>
                <p><strong>アカウント名</strong>　　{{ form.username }}</p>
                    <div class="note">
                        <div class="note_title"><p>個人の情報</p></div>
                        <p>アカウントがビジネス、ペットなどに使用されている場合でも、<br>個人の情報を入力してください。これは公開プロフィールでは表示されません。</p>
                    </div>
                <p><strong>メールアドレス</strong>　{{ form.email }}</p>
                <p><strong>年齢</strong>　　　　　　{{ form.age }}</p>
                <p><strong>性別</strong>　　　　　　{{ form.gender }}</p>
                <p><input class="btn btn-primary" style="margin-right: 20%; margin-top: 0; width: 60%" type="submit" value="変更する"></p>
            </div>
        </form>
    </div>
</div>


{% endblock content %}